---
abstract: 'Provides the C<loop BLOCK> syntax for unconditional loops.'
author:
  - 'Eric Brine <ikegami@adaelis.com>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3614
  Software::License::CC0_1_0: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: feature-loop
provides:
  feature::loop:
    file: lib/feature/loop.pm
    version: v1.3.0
requires:
  Devel::CallParser: 0
  Lexical::Sub: 0
  XSLoader: 0
  perl: 5.014
  version: 0
resources:
  license: http://creativecommons.org/publicdomain/zero/1.0/
version: v1.2.0
